<?php

namespace Database\Seeders;

use App\Models\CourseCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CourseCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $course_categories = [

            /* =========================
             * Web Development
             * ========================= */
            [
                'id' => 1,
                'image' => null,
                'icon' => null,
                'name' => 'Web Development',
                'slug' => 'web-development',
                'parent_id' => null,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'image' => null,
                'icon' => null,
                'name' => 'Web Development(Frontend)',
                'slug' => 'web-development-frontend',
                'parent_id' => 1,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'image' => null,
                'icon' => null,
                'name' => 'Web Development(Backend)',
                'slug' => 'web-development-backend',
                'parent_id' => 1,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'image' => null,
                'icon' => null,
                'name' => 'Web Development-Backend(Nodejs)',
                'slug' => 'web-development-backend-nodejs',
                'parent_id' => 1,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'image' => null,
                'icon' => null,
                'name' => 'Full Stack Web Development',
                'slug' => 'full-stack-web-development',
                'parent_id' => 1,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
             * Programming
             * ========================= */
            [
                'id' => 6,
                'image' => null,
                'icon' => null,
                'name' => 'Programming',
                'slug' => 'programming',
                'parent_id' => null,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'image' => null,
                'icon' => null,
                'name' => 'C Programming',
                'slug' => 'c-programming',
                'parent_id' => 6,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'image' => null,
                'icon' => null,
                'name' => 'C++ Programming',
                'slug' => 'cpp-programming',
                'parent_id' => 6,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'image' => null,
                'icon' => null,
                'name' => 'C# Programming',
                'slug' => 'csharp-programming',
                'parent_id' => 6,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'image' => null,
                'icon' => null,
                'name' => 'Java I',
                'slug' => 'java-i',
                'parent_id' => 6,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'image' => null,
                'icon' => null,
                'name' => 'Java Backend(Spring Boot)',
                'slug' => 'java-backend-spring-boot',
                'parent_id' => 6,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'image' => null,
                'icon' => null,
                'name' => 'Python',
                'slug' => 'python',
                'parent_id' => 6,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
             * Design & Multimedia
             * ========================= */
            [
                'id' => 13,
                'image' => null,
                'icon' => null,
                'name' => 'Design & Multimedia',
                'slug' => 'design-multimedia',
                'parent_id' => null,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'image' => null,
                'icon' => null,
                'name' => 'UX/UI Design',
                'slug' => 'ux-ui-design',
                'parent_id' => 13,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'image' => null,
                'icon' => null,
                'name' => 'Graphic Design',
                'slug' => 'graphic-design',
                'parent_id' => 13,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'image' => null,
                'icon' => null,
                'name' => 'Video Editing',
                'slug' => 'video-editing',
                'parent_id' => 13,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
             * Mobile & Networking
             * ========================= */
            [
                'id' => 17,
                'image' => null,
                'icon' => null,
                'name' => 'Mobile & Networking',
                'slug' => 'mobile-networking',
                'parent_id' => null,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'image' => null,
                'icon' => null,
                'name' => 'Mobile App (Android)',
                'slug' => 'mobile-app-android',
                'parent_id' => 17,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'image' => null,
                'icon' => null,
                'name' => 'Mobile App (flutter)',
                'slug' => 'mobile-app-ios',
                'parent_id' => 17,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'image' => null,
                'icon' => null,
                'name' => 'Networking',
                'slug' => 'networking',
                'parent_id' => 17,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
             * Data & Analytics
             * ========================= */
            [
                'id' => 20,
                'image' => null,
                'icon' => null,
                'name' => 'Data & Analytics',
                'slug' => 'data-analytics',
                'parent_id' => null,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'image' => null,
                'icon' => null,
                'name' => 'Data Analysist',
                'slug' => 'data-analysist',
                'parent_id' => 20,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'image' => null,
                'icon' => null,
                'name' => 'Deep Learning',
                'slug' => 'deep-learning',
                'parent_id' => 20,
                'show_at_trending' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'image' => null,
                'icon' => null,
                'name' => 'Microsoft Power BI',
                'slug' => 'microsoft-power-bi',
                'parent_id' => 20,
                'show_at_trending' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
             * Business & Office
             * ========================= */
            [
                'id' => 24,
                'image' => null,
                'icon' => null,
                'name' => 'Business & Office',
                'slug' => 'business-office',
                'parent_id' => null,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'image' => null,
                'icon' => null,
                'name' => 'Advance of Exel',
                'slug' => 'advance-of-exel',
                'parent_id' => 24,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'image' => null,
                'icon' => null,
                'name' => 'Exel VBA',
                'slug' => 'exel-vba',
                'parent_id' => 24,
                'show_at_trending' => 0,
                'status' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'image' => null,
                'icon' => null,
                'name' => 'Microsoft Office',
                'slug' => 'microsoft-office',
                'parent_id' => 24,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'image' => null,
                'icon' => null,
                'name' => 'Digital Marketing',
                'slug' => 'digital-marketing',
                'parent_id' => 24,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'image' => null,
                'icon' => null,
                'name' => 'IT Project Management',
                'slug' => 'it-project-management',
                'parent_id' => 24,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =========================
             * System & Cloud
             * ========================= */
            [
                'id' => 30,
                'image' => null,
                'icon' => null,
                'name' => 'System & Cloud',
                'slug' => 'system-cloud',
                'parent_id' => null,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'image' => null,
                'icon' => null,
                'name' => 'Database Management System',
                'slug' => 'database-management-system',
                'parent_id' => 30,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'image' => null,
                'icon' => null,
                'name' => 'Cloud Computing',
                'slug' => 'cloud-computing',
                'parent_id' => 30,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'image' => null,
                'icon' => null,
                'name' => 'DevOps',
                'slug' => 'devops',
                'parent_id' => 30,
                'show_at_trending' => 0,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        CourseCategory::insert($course_categories);
    }
}
