<?php

namespace Database\Seeders;

use App\Models\ICTCourse;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ICTCourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $i_c_t_courses = [
            [
                'id' => 48,
                'instructor_id' => 14,
                'schedule_id' => 9,
                'thumbnail' => '/default-images/ict-courses/data_anal.jpg',
                'title' => 'Data Analyst',
                'slug' => 'data-analyst',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 45.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 34,
                'instructor_id' => 27,
                'schedule_id' => 9,
                'thumbnail' => '/default-images/ict-courses/java_i.jpg',
                'title' => 'Java I',
                'slug' => 'java-i',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-30',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:08:54',
            ],
            [
                'id' => 21,
                'instructor_id' => 23,
                'schedule_id' => 2,
                'thumbnail' => '/default-images/ict-courses/graphic_design.jpg',
                'title' => 'Graphic Design',
                'slug' => 'graphic-design',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:07:09',
            ],
            [
                'id' => 24,
                'instructor_id' => 21,
                'schedule_id' => 9,
                'thumbnail' => '/default-images/ict-courses/networking.jpg',
                'title' => 'Networking',
                'slug' => 'networking',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:02:37',
            ],
            [
                'id' => 8,
                'instructor_id' => 14,
                'schedule_id' => 5,
                'thumbnail' => '/default-images/ict-courses/advance_excel.jpg',
                'title' => 'Advance of Excel',
                'slug' => 'advance-of-excel',
                'description' => null,
                'price' => 99,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:15:29',
            ],
            [
                'id' => 40,
                'instructor_id' => 14,
                'schedule_id' => 3,
                'thumbnail' => '/default-images/ict-courses/cplus.jpg',
                'title' => 'C Programming',
                'slug' => 'c-programming',
                'description' => null,
                'price' => 119,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-30',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:17:43',
            ],
            [
                'id' => 31,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/csharp.jpg',
                'title' => 'C# Programming',
                'slug' => 'c-programming',
                'description' => null,
                'price' => 159,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-30',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:18:45',
            ],
            [
                'id' => 3,
                'instructor_id' => 14,
                'schedule_id' => 6,
                'thumbnail' => '/default-images/ict-courses/cplus.jpg',
                'title' => 'C++ Programming',
                'slug' => 'c++-programming',
                'description' => null,
                'price' => 89,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 30,
                'instructor_id' => 14,
                'schedule_id' => 4,
                'thumbnail' => '/default-images/ict-courses/cplus.jpg',
                'title' => 'C++ Programming',
                'slug' => 'c++-programming',
                'description' => null,
                'price' => 89,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 43,
                'instructor_id' => 14,
                'schedule_id' => 8,
                'thumbnail' => '/default-images/ict-courses/cplus.jpg',
                'title' => 'C++ Programming',
                'slug' => 'c++-programming',
                'description' => null,
                'price' => 89,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 12,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/devops.jpg',
                'title' => 'Cloud Computing',
                'slug' => 'cloud-computing',
                'description' => null,
                'price' => 159,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 17,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/cyber_sec.jpg',
                'title' => 'Cyber Security',
                'slug' => 'cyber-security',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 23,
                'instructor_id' => 14,
                'schedule_id' => 2,
                'thumbnail' => '/default-images/ict-courses/data_anal.jpg',
                'title' => 'Data Analyst',
                'slug' => 'data-analyst',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 9,
                'instructor_id' => 14,
                'schedule_id' => 5,
                'thumbnail' => '/default-images/ict-courses/dbms.jpg',
                'title' => 'Database Management System',
                'slug' => 'database-management-system',
                'description' => null,
                'price' => 159,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 13,
                'instructor_id' => 14,
                'schedule_id' => 5,
                'thumbnail' => '/default-images/ict-courses/data_anal.jpg',
                'title' => 'Deep Learning',
                'slug' => 'deep-learning',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 38,
                'instructor_id' => 14,
                'schedule_id' => 5,
                'thumbnail' => '/default-images/ict-courses/data_anal.jpg',
                'title' => 'Deep Learning',
                'slug' => 'deep-learning',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-30',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 15,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/devops.jpg',
                'title' => 'DevOps',
                'slug' => 'devops',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 53,
                'instructor_id' => 14,
                'schedule_id' => 7,
                'thumbnail' => '/default-images/ict-courses/digital_marketing.jpg',
                'title' => 'Digital Marketing',
                'slug' => 'digital-marketing',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 37,
                'instructor_id' => 14,
                'schedule_id' => 3,
                'thumbnail' => '/default-images/ict-courses/advance_excel.jpg',
                'title' => 'Excel VBA',
                'slug' => 'excel-vba',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 10,
                'instructor_id' => 14,
                'schedule_id' => 4,
                'thumbnail' => '/default-images/ict-courses/advance_excel.jpg',
                'title' => 'Excel VBA',
                'slug' => 'excel-vba',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 50,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/web_dev_front.jpg',
                'title' => 'Full Stack Web Development',
                'slug' => 'full-stack-web-development',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-27',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 14,
                'instructor_id' => 14,
                'schedule_id' => 7,
                'thumbnail' => '/default-images/ict-courses/it_pro_manage.jpg',
                'title' => 'IT Project Management',
                'slug' => 'it-project-management',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 26,
                'instructor_id' => 14,
                'schedule_id' => 6,
                'thumbnail' => '/default-images/ict-courses/it_pro_manage.jpg',
                'title' => 'IT Project Management',
                'slug' => 'it-project-management',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 52,
                'instructor_id' => 14,
                'schedule_id' => 5,
                'thumbnail' => '/default-images/ict-courses/soft_dev_java.jpg',
                'title' => 'Java Backend (Spring Boot)',
                'slug' => 'java-backend-spring-boot',
                'description' => null,
                'price' => 139,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 11,
                'instructor_id' => 14,
                'schedule_id' => 5,
                'thumbnail' => '/default-images/ict-courses/soft_dev_java.jpg',
                'title' => 'Java Backend (Spring Boot)',
                'slug' => 'java-backend-spring-boot',
                'description' => null,
                'price' => 139,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 49,
                'instructor_id' => 14,
                'schedule_id' => 9,
                'thumbnail' => '/default-images/ict-courses/java_i.jpg',
                'title' => 'Java I',
                'slug' => 'java-i',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:14:41',
            ],
            [
                'id' => 18,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/data_anal.jpg',
                'title' => 'Machine Learning',
                'slug' => 'machine-learning',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 36,
                'instructor_id' => 14,
                'schedule_id' => 3,
                'thumbnail' => '/default-images/ict-courses/microsoft_office.jpg',
                'title' => 'Microsoft Office',
                'slug' => 'microsoft-office',
                'description' => null,
                'price' => 69,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 41,
                'instructor_id' => 14,
                'schedule_id' => 8,
                'thumbnail' => '/default-images/ict-courses/data_anal.jpg',
                'title' => 'Microsoft Power BI',
                'slug' => 'microsoft-power-bi',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5.5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 16,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/data_anal.jpg',
                'title' => 'Microsoft Power BI',
                'slug' => 'microsoft-power-bi',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 5,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/mobile_app_flutter_dart.jpg',
                'title' => 'Mobile App',
                'slug' => 'mobile-app',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 20,
                'instructor_id' => 14,
                'schedule_id' => 2,
                'thumbnail' => '/default-images/ict-courses/mobile_app_flutter_dart.jpg',
                'title' => 'Mobile App (Android)',
                'slug' => 'mobile-app-android',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 45,
                'instructor_id' => 14,
                'schedule_id' => 9,
                'thumbnail' => '/default-images/ict-courses/mobile_app_flutter_dart.jpg',
                'title' => 'Mobile App (Flutter)',
                'slug' => 'mobile-app-flutter',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 25,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/networking.jpg',
                'title' => 'Networking',
                'slug' => 'networking',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 51,
                'instructor_id' => 14,
                'schedule_id' => 9,
                'thumbnail' => '/default-images/ict-courses/networking.jpg',
                'title' => 'Networking',
                'slug' => 'networking',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 33,
                'instructor_id' => 14,
                'schedule_id' => 3,
                'thumbnail' => '/default-images/ict-courses/python_programming.jpg',
                'title' => 'Python',
                'slug' => 'python',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-30',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 47,
                'instructor_id' => 14,
                'schedule_id' => 9,
                'thumbnail' => '/default-images/ict-courses/python_programming.jpg',
                'title' => 'Python',
                'slug' => 'python',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 44,
                'instructor_id' => 14,
                'schedule_id' => 4,
                'thumbnail' => '/default-images/ict-courses/ux_ui_design.jpg',
                'title' => 'UX/UI Design',
                'slug' => 'ux/ui-design',
                'description' => null,
                'price' => 119,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 19,
                'instructor_id' => 14,
                'schedule_id' => 2,
                'thumbnail' => '/default-images/ict-courses/ux_ui_design.jpg',
                'title' => 'UX/UI Design',
                'slug' => 'ux/ui-design',
                'description' => null,
                'price' => 119,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-30',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 32,
                'instructor_id' => 14,
                'schedule_id' => 4,
                'thumbnail' => '/default-images/ict-courses/ux_ui_design.jpg',
                'title' => 'UX/UI Design',
                'slug' => 'ux/ui-design',
                'description' => null,
                'price' => 119,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 4,
                'instructor_id' => 14,
                'schedule_id' => 10,
                'thumbnail' => '/default-images/ict-courses/ux_ui_design.jpg',
                'title' => 'UX/UI Design',
                'slug' => 'ux/ui-design',
                'description' => null,
                'price' => 119,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 39,
                'instructor_id' => 14,
                'schedule_id' => 3,
                'thumbnail' => '/default-images/ict-courses/vid_edit.jpg',
                'title' => 'Video Editing',
                'slug' => 'video-editing',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 27,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/vid_edit.jpg',
                'title' => 'Video Editing',
                'slug' => 'video-editing',
                'description' => null,
                'price' => 149,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-30',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 42,
                'instructor_id' => 14,
                'schedule_id' => 4,
                'thumbnail' => '/default-images/ict-courses/web_dev_front.jpg',
                'title' => 'Web Development (Frontend)',
                'slug' => 'web-development-frontend',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-21',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 35,
                'instructor_id' => 14,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/web_dev_back.jpg',
                'title' => 'Web Development Backend (NodeJs)',
                'slug' => 'web-development-backend-nodejs',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-27',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-28 12:00:00',
            ],
            [
                'id' => 2,
                'instructor_id' => 13,
                'schedule_id' => 4,
                'thumbnail' => '/default-images/ict-courses/web_dev_back.jpg',
                'title' => 'Web Development (Backend)',
                'slug' => 'web-development-backend',
                'description' => null,
                'price' => 139,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:05:40',
            ],
            [
                'id' => 22,
                'instructor_id' => 11,
                'schedule_id' => 9,
                'thumbnail' => '/default-images/ict-courses/python_programming.jpg',
                'title' => 'Python',
                'slug' => 'python',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:01:40',
            ],
            [
                'id' => 28,
                'instructor_id' => 10,
                'schedule_id' => 4,
                'thumbnail' => '/default-images/ict-courses/web_dev_front.jpg',
                'title' => 'Web Development (Frontend)',
                'slug' => 'web-development-frontend',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-30',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 15:59:01',
            ],
            [
                'id' => 46,
                'instructor_id' => 8,
                'schedule_id' => 8,
                'thumbnail' => '/default-images/ict-courses/graphic_design.jpg',
                'title' => 'Graphic Design',
                'slug' => 'graphic-design',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:07:42',
            ],
            [
                'id' => 29,
                'instructor_id' => 5,
                'schedule_id' => 4,
                'thumbnail' => '/default-images/ict-courses/web_dev_back.jpg',
                'title' => 'Web Development (Backend)',
                'slug' => 'web-development-backend',
                'description' => null,
                'price' => 139,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 15:56:56',
            ],
            [
                'id' => 1,
                'instructor_id' => 3,
                'schedule_id' => 1,
                'thumbnail' => '/default-images/ict-courses/web_dev_front.jpg',
                'title' => 'Web Development (Frontend)',
                'slug' => 'web-development-frontend',
                'description' => null,
                'price' => 129,
                'price_per_session' => 5,
                'duration' => 48.00,
                'status' => 'active',
                'start_date' => '2026-05-25',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 15:57:48',
            ],
            [
                'id' => 7,
                'instructor_id' => 9,
                'schedule_id' => 8,
                'thumbnail' => '/default-images/ict-courses/web_dev_front.jpg',
                'title' => 'Full Stack Web Development',
                'slug' => 'full-stack-web-development',
                'description' => null,
                'price' => 159,
                'price_per_session' => 6,
                'duration' => 60.00,
                'status' => 'active',
                'start_date' => '2026-05-26',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:04:26',
            ],
            [
                'id' => 6,
                'instructor_id' => 9,
                'schedule_id' => 5,
                'thumbnail' => '/default-images/ict-courses/web_dev_front.jpg',
                'title' => 'Full Stack Web Development',
                'slug' => 'full-stack-web-development',
                'description' => null,
                'price' => 159,
                'price_per_session' => 6,
                'duration' => 60.00,
                'status' => 'active',
                'start_date' => '2026-05-24',
                'end_date' => null,
                'created_at' => '2026-04-28 12:00:00',
                'updated_at' => '2026-04-30 16:03:47',
            ],
        ];


        ICTCourse::insert($i_c_t_courses);

        // foreach ($i_c_t_courses as $course) {
        //     DB::table('i_c_t_courses')->insert([
        //         'id' => $course['id'],
        //         'instructor_id' => $course['instructor_id'],
        //         'schedule_id' => $course['schedule_id'],
        //         'thumbnail' => $course['thumbnail'],
        //         'title' => $course['title'],
        //         'slug' => $course['slug'],
        //         'description' => $course['description'],

        //         // ✅ ADDED ONLY THESE TWO
        //         'start_date' => now()->addDays(rand(1, 30))->format('Y-m-d'),
        //         'duration' => rand(40, 100),

        //         'price' => $course['price'],
        //         'status' => $course['status'],
        //         'created_at' => $course['created_at'],
        //         'updated_at' => $course['updated_at'],
        //     ]);
        // }



    }
}
