<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = [
            [
                'name' => 'Chantheoun Sokvibol',
                'email' => 'chantheoun.sokvibol@example.com',
                'image' => '/default-images/teacher/vibol.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muth Manou',
                'email' => 'muth.manou@example.com',
                'image' => '/default-images/teacher/manou.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sin Many',
                'email' => 'sin.many@example.com',
                'image' => '/default-images/teacher/mony.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khorn sopheap',
                'email' => 'khorn.sopheap@example.com',
                'image' => '/default-images/teacher/sopheab.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Srun Borath',
                'email' => 'srun.borath@example.com',
                'image' => '/default-images/teacher/borath.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hong Kimleng',
                'email' => 'hong.kimleng@example.com',
                'image' => '/default-images/teacher/kimleng.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phally Makara',
                'email' => 'phally.makara@example.com',
                'image' => '/default-images/teacher/makara.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yeab Chanya',
                'email' => 'yeab.chanya@example.com',
                'image' => '/default-images/teacher/chanya.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lay Longhav',
                'email' => 'lay.longhav@example.com',
                'image' => '/default-images/teacher/longhav.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ang Kimsor',
                'email' => 'ang.kimsor@example.com',
                'image' => '/default-images/teacher/kimsor.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ngan Channa',
                'email' => 'ngan.channa@example.com',
                'image' => '/default-images/teacher/chana.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chea Dane',
                'email' => 'chea.dane@example.com',
                'image' => '/default-images/teacher/dane.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tiv Sovithyea',
                'email' => 'tiv.sovithyea@example.com',
                'image' => '/default-images/teacher/sovith.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'teacher',
                'email' => 'teacher@gmail.com',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'student',
                'email' => 'student@gmail.com',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        User::insert($user);
    }
}
