<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;


class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = [
            [
                'name' => 'Chantheoun Sokvibol',
                'email' => 'chantheoun.sokvibol@example.com',
                'phone' => '012111222',
                'gender' => 'male',
                'image' => '/default-images/teacher/vibol.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muth Manou',
                'email' => 'muth.manou@example.com',
                'phone' => '015333444',
                'gender' => 'female',
                'image' => '/default-images/teacher/manou.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Siem Reap',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sin Many',
                'email' => 'sin.many@example.com',
                'phone' => '017555666',
                'gender' => 'male',
                'image' => '/default-images/teacher/mony.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'on_leave',
                'location' => 'Battambang',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khorn sopheap',
                'email' => 'khorn.sopheap@example.com',
                'phone' => '093777888',
                'gender' => 'female',
                'image' => '/default-images/teacher/sopheab.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Kampot',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Srun Borath',
                'email' => 'srun.borath@example.com',
                'phone' => '010999000',
                'gender' => 'male',
                'image' => '/default-images/teacher/borath.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Kandal',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hong Kimleng',
                'email' => 'hong.kimleng@example.com',
                'phone' => '012222333',
                'gender' => 'male',
                'image' => '/default-images/teacher/kimleng.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phally Makara',
                'email' => 'phally.makara@example.com',
                'phone' => '015444555',
                'gender' => 'male',
                'image' => '/default-images/teacher/makara.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Sihanoukville',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yeab Chanya',
                'email' => 'yeab.chanya@example.com',
                'phone' => '017666777',
                'gender' => 'female',
                'image' => '/default-images/teacher/chanya.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Takeo',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lay Longhav',
                'email' => 'lay.longhav@example.com',
                'phone' => '093888999',
                'gender' => 'male',
                'image' => '/default-images/teacher/longhav.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Kampong Cham',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ang Kimsor',
                'email' => 'ang.kimsor@example.com',
                'phone' => '010123456',
                'gender' => 'female',
                'image' => '/default-images/teacher/kimsor.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ngan Channa',
                'email' => 'ngan.channa@example.com',
                'phone' => '012654321',
                'gender' => 'female',
                'image' => '/default-images/teacher/chana.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Prey Veng',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chea Dane',
                'email' => 'chea.dane@example.com',
                'phone' => '015987654',
                'gender' => 'female',
                'image' => '/default-images/teacher/dane.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tiv Sovithyea',
                'email' => 'tiv.sovithyea@example.com',
                'phone' => '017111333',
                'gender' => 'male',
                'image' => '/default-images/teacher/sovith.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Siem Reap',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'teacher',
                'email' => 'teacher@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'student',
                'email' => 'student@gmail.com',
                'phone' => '015000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Channy',
                'email' => 'staff@gmail.com',
                'phone' => '017000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'staff',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        User::insert($user);
    }
}
