<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;


class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Chantheoun Sokvibol',
                'khmer_name' => 'ចន្ធឿន សុខវិបុល',
                'dob' => '1990-01-15',
                'email' => 'chantheounsokvibol@gmail.com',
                'phone' => '012111222',
                'gender' => 'male',
                'image' => '/default-images/teacher/vibol.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muth Manou',
                'khmer_name' => 'មុត មានូ',
                'dob' => '1992-03-22',
                'email' => 'muthmanou@gmail.com',
                'phone' => '015333444',
                'gender' => 'female',
                'image' => '/default-images/teacher/manou.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Siem Reap',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sin Many',
                'khmer_name' => 'សិន មានី',
                'dob' => '1988-07-10',
                'email' => 'sinmany@gmail.com',
                'phone' => '0886610148',
                'gender' => 'male',
                'image' => '/default-images/teacher/mony.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'on_leave',
                'location' => 'Battambang',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khorn sopheap',
                'khmer_name' => 'ខន សុភាព',
                'dob' => '1993-05-18',
                'email' => 'khornsopheap@gmail.com',
                'phone' => '093777888',
                'gender' => 'female',
                'image' => '/default-images/teacher/sopheab.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Kampot',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Srun Borath',
                'khmer_name' => 'ស្រុន បូរ័ត្ន',
                'dob' => '1991-11-04',
                'email' => 'srunborath@gmail.com',
                'phone' => '0974242291',
                'gender' => 'male',
                'image' => '/default-images/teacher/borath.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hong Kimleng',
                'khmer_name' => 'ហុង គីមឡេង',
                'dob' => '1989-08-25',
                'email' => 'hongkimleng@gamil.com',
                'phone' => '012222333',
                'gender' => 'male',
                'image' => '/default-images/teacher/kimleng.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phally Makara',
                'khmer_name' => 'ផល្លី មករា',
                'dob' => '1994-02-14',
                'email' => 'phallymakara@gmail.com',
                'phone' => '089804659',
                'gender' => 'male',
                'image' => '/default-images/teacher/makara.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Sihanoukville',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yeab Chanya',
                'khmer_name' => 'យ៉ាប ចន្យា',
                'dob' => '1995-06-30',
                'email' => 'yeabchanya@gamil.com',
                'phone' => '017666777',
                'gender' => 'female',
                'image' => '/default-images/teacher/chanya.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Takeo',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lay Longhav',
                'khmer_name' => 'លី លោងហាវ',
                'dob' => '1987-09-12',
                'email' => 'laylonghav@gmail.com',
                'phone' => '093888999',
                'gender' => 'male',
                'image' => '/default-images/teacher/longhav.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Kampong Cham',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ang Kimsor',
                'khmer_name' => 'អង គីមសុរ',
                'dob' => '1996-04-07',
                'email' => 'angkimsor@gmail.com',
                'phone' => '087932289',
                'gender' => 'female',
                'image' => '/default-images/teacher/kimsor.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ngan Channa',
                'khmer_name' => 'ង៉ាន ចន្នា',
                'dob' => '1993-12-19',
                'email' => 'nganchanna@gmail.com',
                'phone' => '012654321',
                'gender' => 'female',
                'image' => '/default-images/teacher/chana.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Prey Veng',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chea Dane',
                'khmer_name' => 'ជា ដានី',
                'dob' => '1994-10-08',
                'email' => 'cheadane@gmail.com',
                'phone' => '015987654',
                'gender' => 'female',
                'image' => '/default-images/teacher/dane.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tiv Sovithyea',
                'khmer_name' => 'តិវ សុវិទ្យា',
                'dob' => '1990-06-15',
                'email' => 'tiv.sovithyea@gmail.com',
                'phone' => '0883786262',
                'gender' => 'male',
                'image' => '/default-images/teacher/sovith.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'teacher',
                'khmer_name' => 'គ្រូបង្រៀន',
                'dob' => '1990-01-01',
                'email' => 'teacher@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'raa',
                'khmer_name' => 'រ៉ា',
                'dob' => '1990-01-01',
                'email' => 'raa@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'student',
                'khmer_name' => 'សិស្ស',
                'dob' => '2000-01-01',
                'email' => 'student@gmail.com',
                'phone' => '015000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reak Sothea',
                'khmer_name' => 'រ៉េក សុធា',
                'dob' => '2001-03-14',
                'email' => 'reak@gmail.com',
                'phone' => '015000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'reach',
                'khmer_name' => 'រ៉ែស',
                'dob' => '2000-06-20',
                'email' => 'reach@gmail.com',
                'phone' => '015000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'rin',
                'khmer_name' => 'រីន',
                'dob' => '2001-09-05',
                'email' => 'rin@gmail.com',
                'phone' => '015000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => ' Tha Channy',
                'khmer_name' => 'ថា ចន្នី',
                'dob' => '1995-07-21',
                'email' => 'staff@gmail.com',
                'phone' => '017000000',
                'gender' => 'female',
                'image' => '/default-images/teacher/Tha Channy.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345679'),
                'role' => 'staff',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thy Narong',
                'khmer_name' => 'ថី នរោង',
                'dob' => '1988-03-17',
                'email' => 'thynarong@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Thy Narong.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Soth Bandethvitou',
                'khmer_name' => 'សុទ្ធ បណ្ដែតវិតូ',
                'dob' => '1991-05-29',
                'email' => 'sothBandethvitou@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Soth Bandethvithou.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sok Vitou',
                'khmer_name' => 'សុខ វិតូ',
                'dob' => '1992-08-11',
                'email' => 'sokvitou@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Sokvitou.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tha Channy',
                'khmer_name' => 'ថា ចន្នី',
                'dob' => '1995-07-21',
                'email' => 'thachanny@gmail.com',
                'phone' => '012000000',
                'gender' => 'female',
                'image' => '/default-images/teacher/Tha Channy.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pich Vorleak',
                'khmer_name' => 'ពេជ្រ វរលក្ខណ៍',
                'dob' => '1993-11-03',
                'email' => 'pichvorleak@gmail.com',
                'phone' => '012000000',
                'gender' => 'female',
                'image' => '/default-images/teacher/Vorleak.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nov sovannet',
                'khmer_name' => 'នូ សុវណ្ណណែត',
                'dob' => '1989-04-26',
                'email' => 'novsovannet@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Nov sovannet.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nhanh Nhim',
                'khmer_name' => 'ញ៉ាំ ញឹម',
                'dob' => '1991-02-08',
                'email' => 'nhanhnhim@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Nhanh nhim.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thy ChanTha',
                'khmer_name' => 'ថី ចន្ថា',
                'dob' => '1990-10-15',
                'email' => 'thychanthat@gmail.com',
                'phone' => '090500427',
                'gender' => 'male',
                'image' => '/default-images/teacher/Thy Chantha.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chan Vimean',
                'khmer_name' => 'ចាន់ វិមាន',
                'dob' => '1992-01-23',
                'email' => 'chanvimean@gmail.com',
                'phone' => '089804644',
                'gender' => 'male',
                'image' => '/default-images/teacher/Chan Vimean.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sao Sothea',
                'khmer_name' => 'សៅ សុធា',
                'dob' => '1993-06-09',
                'email' => 'saosothea@gmail.com',
                'phone' => '090426632',
                'gender' => 'male',
                'image' => '/default-images/teacher/Sao Sothea.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nut Dalitongsin',
                'khmer_name' => 'នូត ដាលីតុងស៊ីន',
                'dob' => '1990-12-30',
                'email' => 'nutdalitongsin@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Nut Dalitongsin.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tha Channy',
                'khmer_name' => 'ថា ចន្នី',
                'dob' => '1995-07-21',
                'email' => 'ny@gmail.com',
                'phone' => '',
                'gender' => 'female',
                'image' => '/default-images/teacher/Tha Channy.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'staff',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dalin',
                'khmer_name' => '',
                'dob' => '1995-07-21',
                'email' => 'lin@gmail.com',
                'phone' => '',
                'gender' => 'female',
                'image' => '',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'staff',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        User::insert($users);
    }
}
