<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;


class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Chantheoun Sokvibol',
                'email' => 'chantheounsokvibol@gmail.com',
                'phone' => '012111222',
                'gender' => 'male',
                'image' => '/default-images/teacher/vibol.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muth Manou',
                'email' => 'muthmanou@gmail.com',
                'phone' => '015333444',
                'gender' => 'female',
                'image' => '/default-images/teacher/manou.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Siem Reap',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sin Many',
                'email' => 'sinmany@gmail.com',
                'phone' => '0886610148',
                'gender' => 'male',
                'image' => '/default-images/teacher/mony.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'on_leave',
                'location' => 'Battambang',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khorn sopheap',
                'email' => 'khornsopheap@gmail.com',
                'phone' => '093777888',
                'gender' => 'female',
                'image' => '/default-images/teacher/sopheab.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Kampot',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Srun Borath',
                'email' => 'srunborath@gmail.com',
                'phone' => '0974242291',
                'gender' => 'male',
                'image' => '/default-images/teacher/borath.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hong Kimleng',
                'email' => 'hongkimleng@gamil.com',
                'phone' => '012222333',
                'gender' => 'male',
                'image' => '/default-images/teacher/kimleng.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phally Makara',
                'email' => 'phallymakara@gmail.com',
                'phone' => '089804659',
                'gender' => 'male',
                'image' => '/default-images/teacher/makara.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Sihanoukville',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yeab Chanya',
                'email' => 'yeabchanya@gamil.com',
                'phone' => '017666777',
                'gender' => 'female',
                'image' => '/default-images/teacher/chanya.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Takeo',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lay Longhav',
                'email' => 'laylonghav@gmail.com',
                'phone' => '093888999',
                'gender' => 'male',
                'image' => '/default-images/teacher/longhav.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Kampong Cham',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ang Kimsor',
                'email' => 'angkimsor@gmail.com',
                'phone' => '087932289',
                'gender' => 'female',
                'image' => '/default-images/teacher/kimsor.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ngan Channa',
                'email' => 'nganchanna@gmail.com',
                'phone' => '012654321',
                'gender' => 'female',
                'image' => '/default-images/teacher/chana.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Prey Veng',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chea Dane',
                'email' => 'cheadane@gmail.com',
                'phone' => '015987654',
                'gender' => 'female',
                'image' => '/default-images/teacher/dane.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tiv Sovithyea',
                'email' => 'tiv.sovithyea@gmail.com',
                'phone' => '0883786262',
                'gender' => 'male',
                'image' => '/default-images/teacher/sovith.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'teacher',
                'email' => 'teacher@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'raa',
                'email' => 'raa@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'student',
                'email' => 'student@gmail.com',
                'phone' => '015000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reak Sothea',
                'email' => 'reak@gmail.com',
                'phone' => '015000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'reach',
                'email' => 'reach@gmail.com',
                'phone' => '015000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'rin',
                'email' => 'rin@gmail.com',
                'phone' => '015000000',
                'gender' => 'female',
                'image' => 'no-img.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'student',
                'approval_status' => 'approved',
                'document' => '',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => ' Tha Channy',
                'email' => 'staff@gmail.com',
                'phone' => '017000000',
                'gender' => 'female',
                'image' => '/default-images/teacher/Tha Channy.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'staff',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thy Narong',
                'email' => 'thynarong@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Thy Narong.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Soth Bandethvitou',
                'email' => 'sothBandethvitou@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Soth Bandethvithou.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sok Vitou',
                'email' => 'sokvitou@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Sokvitou.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tha Channy',
                'email' => 'thachanny@gmail.com',
                'phone' => '012000000',
                'gender' => 'female',
                'image' => '/default-images/teacher/Tha Channy.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pich Vorleak',
                'email' => 'pichvorleak@gmail.com',
                'phone' => '012000000',
                'gender' => 'female',
                'image' => '/default-images/teacher/Vorleak.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nov sovannet',
                'email' => 'novsovannet@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Nov sovannet.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nhanh Nhim',
                'email' => 'nhanhnhim@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Nhanh nhim.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thy ChanTha',
                'email' => 'thychanthat@gmail.com',
                'phone' => '090500427',
                'gender' => 'male',
                'image' => '/default-images/teacher/Thy Chantha.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chan Vimean',
                'email' => 'chanvimean@gmail.com',
                'phone' => '089804644',
                'gender' => 'male',
                'image' => '/default-images/teacher/Chan Vimean.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sao Sothea',
                'email' => 'saosothea@gmail.com',
                'phone' => '090426632',
                'gender' => 'male',
                'image' => '/default-images/teacher/Sao Sothea.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nut Dalitongsin',
                'email' => 'nutdalitongsin@gmail.com',
                'phone' => '012000000',
                'gender' => 'male',
                'image' => '/default-images/teacher/Nut Dalitongsin.JPG',
                'email_verified_at' => now(),
                'password' => bcrypt('12345678'),
                'role' => 'instructor',
                'approval_status' => 'approved',
                'document' => 'document.jpg',
                'status' => 'active',
                'location' => 'Phnom Penh',
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        User::insert($users);
    }
}
