<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('intern_reports', function (Blueprint $table): void {
            $table->id();

            $table->foreignId('reported_by')
                ->constrained('users')
                ->cascadeOnDelete();

            // HTML generated by TinyMCE
            $table->longText('report_content');

            $table->enum('status', [
                'pending',
                'reviewed',
            ])->default('pending');

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('intern_reports');
    }
};
